<?php

namespace Database\Seeders;

use App\Models\Brand;
use App\Models\Category;
use App\Models\Product;
use App\Models\StockItem;
use App\Models\StockMovement;
use App\Models\User;
use Illuminate\Database\Seeder;

class DemoCatalogSeeder extends Seeder
{
    public function run(): void
    {
        $actor = User::query()->where('email', 'catalog.manager@example.com')->first()
            ?? User::query()->where('email', 'admin@example.com')->first();

        $categories = [
            'dresses' => Category::query()->firstWhere('slug', 'dresses'),
            'tops' => Category::query()->firstWhere('slug', 'tops'),
            'shirts' => Category::query()->firstWhere('slug', 'shirts'),
            'trousers' => Category::query()->firstWhere('slug', 'trousers'),
            'school-wear' => Category::query()->firstWhere('slug', 'school-wear'),
            'play-wear' => Category::query()->firstWhere('slug', 'play-wear'),
            'footwear' => Category::query()->firstWhere('slug', 'footwear'),
            'sandals' => Category::query()->firstWhere('slug', 'sandals'),
            'sneakers' => Category::query()->firstWhere('slug', 'sneakers'),
            'bags' => Category::query()->firstWhere('slug', 'bags'),
            'work-bags' => Category::query()->firstWhere('slug', 'work-bags'),
            'crossbody-bags' => Category::query()->firstWhere('slug', 'crossbody-bags'),
            'accessories' => Category::query()->firstWhere('slug', 'accessories'),
            'fragrance' => Category::query()->firstWhere('slug', 'fragrance'),
            'skin-care' => Category::query()->firstWhere('slug', 'skin-care'),
            'decor' => Category::query()->firstWhere('slug', 'decor'),
            'bed-bath' => Category::query()->firstWhere('slug', 'bed-bath'),
        ];

        $brands = [
            'urban-step' => Brand::query()->firstWhere('slug', 'urban-step'),
            'lasid-basics' => Brand::query()->firstWhere('slug', 'lasid-basics'),
            'adma-studio' => Brand::query()->firstWhere('slug', 'adma-studio'),
            'northline-home' => Brand::query()->firstWhere('slug', 'northline-home'),
            'gold-coast-care' => Brand::query()->firstWhere('slug', 'gold-coast-care'),
        ];

        $products = [
            [
                'sku' => 'LAS-SNK-001',
                'category_slug' => 'sneakers',
                'brand_slug' => 'urban-step',
                'name' => 'Urban Sprint Sneaker',
                'slug' => 'urban-sprint-sneaker',
                'short_description' => 'Everyday lightweight sneaker for fast city movement.',
                'description' => 'A breathable low-top sneaker built for daily wear, with cushioned comfort and a clean profile for storefront demos.',
                'base_price' => 32500,
                'compare_at_price' => 39000,
                'cost_price' => 18000,
                'track_inventory' => true,
                'allow_backorders' => false,
                'is_featured' => true,
                'published_at' => now()->subDays(14),
                'quantity_on_hand' => 30,
                'quantity_reserved' => 4,
                'reorder_level' => 8,
            ],
            [
                'sku' => 'LAS-SND-002',
                'category_slug' => 'sandals',
                'brand_slug' => 'urban-step',
                'name' => 'Coastline Slide Sandal',
                'slug' => 'coastline-slide-sandal',
                'short_description' => 'Easy slip-on sandal for casual warm-weather wear.',
                'description' => 'A minimal slide sandal used to demonstrate secondary footwear categories and lower price points.',
                'base_price' => 18500,
                'compare_at_price' => 22000,
                'cost_price' => 9000,
                'track_inventory' => true,
                'allow_backorders' => false,
                'is_featured' => false,
                'published_at' => now()->subDays(10),
                'quantity_on_hand' => 12,
                'quantity_reserved' => 1,
                'reorder_level' => 5,
            ],
            [
                'sku' => 'LAS-BAG-003',
                'category_slug' => 'work-bags',
                'brand_slug' => 'lasid-basics',
                'name' => 'Metro Carry Tote',
                'slug' => 'metro-carry-tote',
                'short_description' => 'Structured tote bag with all-day storage.',
                'description' => 'A versatile carry tote used for featured merchandising and bundled cart demos.',
                'base_price' => 27500,
                'compare_at_price' => 32000,
                'cost_price' => 15000,
                'track_inventory' => true,
                'allow_backorders' => false,
                'is_featured' => true,
                'published_at' => now()->subDays(7),
                'quantity_on_hand' => 18,
                'quantity_reserved' => 2,
                'reorder_level' => 6,
            ],
            [
                'sku' => 'LAS-CAP-004',
                'category_slug' => 'accessories',
                'brand_slug' => 'lasid-basics',
                'name' => 'Signature Street Cap',
                'slug' => 'signature-street-cap',
                'short_description' => 'Classic cap with adjustable fit and embroidered front.',
                'description' => 'Useful for admin catalog demos because it shows a simpler accessory record with healthy stock.',
                'base_price' => 9500,
                'compare_at_price' => 12000,
                'cost_price' => 4500,
                'track_inventory' => true,
                'allow_backorders' => false,
                'is_featured' => false,
                'published_at' => now()->subDays(5),
                'quantity_on_hand' => 40,
                'quantity_reserved' => 3,
                'reorder_level' => 10,
            ],
            [
                'sku' => 'LAS-WLT-005',
                'category_slug' => 'accessories',
                'brand_slug' => 'lasid-basics',
                'name' => 'Contour Leather Wallet',
                'slug' => 'contour-leather-wallet',
                'short_description' => 'Compact everyday wallet with multiple card slots.',
                'description' => 'Designed to show a premium accessory with low available inventory for dashboard demos.',
                'base_price' => 16500,
                'compare_at_price' => 21000,
                'cost_price' => 9200,
                'track_inventory' => true,
                'allow_backorders' => false,
                'is_featured' => true,
                'published_at' => now()->subDays(3),
                'quantity_on_hand' => 6,
                'quantity_reserved' => 2,
                'reorder_level' => 5,
            ],
            [
                'sku' => 'ADM-DRS-006',
                'category_slug' => 'dresses',
                'brand_slug' => 'adma-studio',
                'name' => 'ADMA Midi Occasion Dress',
                'slug' => 'adma-midi-occasion-dress',
                'short_description' => 'Soft-structure midi dress for events and evening styling.',
                'description' => 'An elevated women\'s dress with polished silhouette details to make the seeded catalog feel less generic.',
                'base_price' => 45500,
                'compare_at_price' => 52000,
                'cost_price' => 26000,
                'track_inventory' => true,
                'allow_backorders' => false,
                'is_featured' => true,
                'published_at' => now()->subDays(12),
                'quantity_on_hand' => 14,
                'quantity_reserved' => 2,
                'reorder_level' => 4,
            ],
            [
                'sku' => 'ADM-TOP-007',
                'category_slug' => 'tops',
                'brand_slug' => 'adma-studio',
                'name' => 'ADMA Linen Wrap Top',
                'slug' => 'adma-linen-wrap-top',
                'short_description' => 'Breathable wrap top for smart-casual everyday wear.',
                'description' => 'A lightweight wrap silhouette to seed women\'s separates and layered styling options.',
                'base_price' => 22800,
                'compare_at_price' => 27500,
                'cost_price' => 12000,
                'track_inventory' => true,
                'allow_backorders' => false,
                'is_featured' => false,
                'published_at' => now()->subDays(9),
                'quantity_on_hand' => 22,
                'quantity_reserved' => 1,
                'reorder_level' => 6,
            ],
            [
                'sku' => 'ADB-SHT-008',
                'category_slug' => 'shirts',
                'brand_slug' => 'adma-studio',
                'name' => 'ADMA Oxford Work Shirt',
                'slug' => 'adma-oxford-work-shirt',
                'short_description' => 'Crisp work shirt cut for office-ready rotation.',
                'description' => 'A menswear staple for catalog demos that need a cleaner top-level category split than generic fashion.',
                'base_price' => 26500,
                'compare_at_price' => 31000,
                'cost_price' => 14500,
                'track_inventory' => true,
                'allow_backorders' => false,
                'is_featured' => false,
                'published_at' => now()->subDays(8),
                'quantity_on_hand' => 19,
                'quantity_reserved' => 2,
                'reorder_level' => 5,
            ],
            [
                'sku' => 'ADB-TRS-009',
                'category_slug' => 'trousers',
                'brand_slug' => 'adma-studio',
                'name' => 'ADMA Tailored Commuter Trouser',
                'slug' => 'adma-tailored-commuter-trouser',
                'short_description' => 'Smart-casual trouser built for weekday wear.',
                'description' => 'A dependable menswear bottom for order demos and higher basket mixes.',
                'base_price' => 29800,
                'compare_at_price' => 35000,
                'cost_price' => 17000,
                'track_inventory' => true,
                'allow_backorders' => false,
                'is_featured' => true,
                'published_at' => now()->subDays(6),
                'quantity_on_hand' => 16,
                'quantity_reserved' => 3,
                'reorder_level' => 5,
            ],
            [
                'sku' => 'KID-UNI-010',
                'category_slug' => 'school-wear',
                'brand_slug' => 'lasid-basics',
                'name' => 'Junior School Set',
                'slug' => 'junior-school-set',
                'short_description' => 'Uniform-ready shirt and shorts combo for school runs.',
                'description' => 'A practical kids category seed for merchandising school and family shopping journeys.',
                'base_price' => 17800,
                'compare_at_price' => 21000,
                'cost_price' => 9200,
                'track_inventory' => true,
                'allow_backorders' => false,
                'is_featured' => false,
                'published_at' => now()->subDays(11),
                'quantity_on_hand' => 24,
                'quantity_reserved' => 4,
                'reorder_level' => 8,
            ],
            [
                'sku' => 'KID-PLY-011',
                'category_slug' => 'play-wear',
                'brand_slug' => 'lasid-basics',
                'name' => 'Weekend Play Set',
                'slug' => 'weekend-play-set',
                'short_description' => 'Soft kids play set for movement and everyday comfort.',
                'description' => 'A high-turn kids item that helps the seeded catalog feel broader and more realistic.',
                'base_price' => 14200,
                'compare_at_price' => 16800,
                'cost_price' => 7600,
                'track_inventory' => true,
                'allow_backorders' => false,
                'is_featured' => false,
                'published_at' => now()->subDays(4),
                'quantity_on_hand' => 28,
                'quantity_reserved' => 2,
                'reorder_level' => 10,
            ],
            [
                'sku' => 'LAS-XBD-012',
                'category_slug' => 'crossbody-bags',
                'brand_slug' => 'lasid-basics',
                'name' => 'Commute Crossbody Mini',
                'slug' => 'commute-crossbody-mini',
                'short_description' => 'Compact crossbody bag for errands and light travel.',
                'description' => 'A small-format bag product that rounds out the bags hierarchy and supports mobile-first storefront demos.',
                'base_price' => 21500,
                'compare_at_price' => 25500,
                'cost_price' => 11800,
                'track_inventory' => true,
                'allow_backorders' => false,
                'is_featured' => false,
                'published_at' => now()->subDays(5),
                'quantity_on_hand' => 20,
                'quantity_reserved' => 2,
                'reorder_level' => 6,
            ],
            [
                'sku' => 'GCC-FRG-013',
                'category_slug' => 'fragrance',
                'brand_slug' => 'gold-coast-care',
                'name' => 'Sunrise Body Mist',
                'slug' => 'sunrise-body-mist',
                'short_description' => 'Fresh daily body mist with citrus opening notes.',
                'description' => 'A beauty-category seed to balance the catalog beyond fashion and accessories.',
                'base_price' => 13200,
                'compare_at_price' => 15800,
                'cost_price' => 6800,
                'track_inventory' => true,
                'allow_backorders' => false,
                'is_featured' => true,
                'published_at' => now()->subDays(13),
                'quantity_on_hand' => 25,
                'quantity_reserved' => 1,
                'reorder_level' => 7,
            ],
            [
                'sku' => 'GCC-SKN-014',
                'category_slug' => 'skin-care',
                'brand_slug' => 'gold-coast-care',
                'name' => 'Cocoa Glow Body Butter',
                'slug' => 'cocoa-glow-body-butter',
                'short_description' => 'Rich body butter for evening skin hydration.',
                'description' => 'A skin-care staple that makes the beauty branch usable in storefront filtering demos.',
                'base_price' => 14800,
                'compare_at_price' => 17600,
                'cost_price' => 7900,
                'track_inventory' => true,
                'allow_backorders' => false,
                'is_featured' => false,
                'published_at' => now()->subDays(10),
                'quantity_on_hand' => 21,
                'quantity_reserved' => 2,
                'reorder_level' => 6,
            ],
            [
                'sku' => 'NHL-DEC-015',
                'category_slug' => 'decor',
                'brand_slug' => 'northline-home',
                'name' => 'Woven Accent Basket',
                'slug' => 'woven-accent-basket',
                'short_description' => 'Decorative woven basket for home organization and styling.',
                'description' => 'A practical home decor item to make non-fashion catalog branches worth demoing.',
                'base_price' => 18900,
                'compare_at_price' => 22500,
                'cost_price' => 10200,
                'track_inventory' => true,
                'allow_backorders' => false,
                'is_featured' => false,
                'published_at' => now()->subDays(7),
                'quantity_on_hand' => 17,
                'quantity_reserved' => 1,
                'reorder_level' => 5,
            ],
            [
                'sku' => 'NHL-BTH-016',
                'category_slug' => 'bed-bath',
                'brand_slug' => 'northline-home',
                'name' => 'Cloud Cotton Bath Set',
                'slug' => 'cloud-cotton-bath-set',
                'short_description' => 'Bath towel set for premium daily home use.',
                'description' => 'A bed-and-bath seed with strong basket-building behavior for demo orders.',
                'base_price' => 24200,
                'compare_at_price' => 29000,
                'cost_price' => 13600,
                'track_inventory' => true,
                'allow_backorders' => false,
                'is_featured' => true,
                'published_at' => now()->subDays(2),
                'quantity_on_hand' => 13,
                'quantity_reserved' => 2,
                'reorder_level' => 4,
            ],
        ];

        foreach ($products as $definition) {
            $product = Product::query()->updateOrCreate(
                ['sku' => $definition['sku']],
                [
                    'category_id' => $categories[$definition['category_slug']]?->getKey(),
                    'brand_id' => $brands[$definition['brand_slug']]?->getKey(),
                    'name' => $definition['name'],
                    'slug' => $definition['slug'],
                    'short_description' => $definition['short_description'],
                    'description' => $definition['description'],
                    'status' => 'active',
                    'product_type' => 'physical',
                    'base_price' => $definition['base_price'],
                    'compare_at_price' => $definition['compare_at_price'],
                    'cost_price' => $definition['cost_price'],
                    'track_inventory' => $definition['track_inventory'],
                    'allow_backorders' => $definition['allow_backorders'],
                    'is_featured' => $definition['is_featured'],
                    'published_at' => $definition['published_at'],
                ]
            );

            $stockItem = StockItem::query()->updateOrCreate(
                ['product_id' => $product->getKey(), 'product_variant_id' => null],
                [
                    'quantity_on_hand' => $definition['quantity_on_hand'],
                    'quantity_reserved' => $definition['quantity_reserved'],
                    'reorder_level' => $definition['reorder_level'],
                ]
            );

            StockMovement::query()->updateOrCreate(
                [
                    'stock_item_id' => $stockItem->getKey(),
                    'type' => 'restock',
                    'reference_type' => Product::class,
                    'reference_id' => $product->getKey(),
                ],
                [
                    'quantity' => $definition['quantity_on_hand'],
                    'note' => 'Demo opening stock balance.',
                    'created_by' => $actor?->getKey(),
                ]
            );
        }
    }
}
